import type { NavItem, Product } from './types';
import { BUNDLE_PRODUCTS, CLOSURE_PRODUCT, WIG_LAUNDRY_PRODUCT } from './data/hairCatalog';
import { carouselImages, fragranceImages, hairImages, packageImages } from './src/assets/images';

export const WHATSAPP_NUMBER = (import.meta.env.VITE_WHATSAPP_NUMBER ?? '27608957481').replace(/\D/g, '');
export const CONTACT_EMAIL = 'bisilebeautyandmakeup@gmail.com';
export const ORDER_EMAIL = 'bisilebeautyandmakeup@mail.com';
export const CONTACT_PHONE = '+27 60 895 7481';

export const getWhatsAppUrl = (message: string) => {
  const base = WHATSAPP_NUMBER ? `https://wa.me/${WHATSAPP_NUMBER}` : 'https://wa.me/';
  return `${base}?text=${encodeURIComponent(message)}`;
};

export const NAV_ITEMS: NavItem[] = [
  { label: 'Shop', path: '/shop' },
  { label: 'Hair', path: '/hair' },
  { label: 'Our Story', path: '/about' },
  { label: 'Contact', path: '/contact' },
];

const perfumeFace = fragranceImages.face;
const perfumeIndoniyamanzi = fragranceImages.indoniyamanzi;
const perfumeInkanyezi = fragranceImages.inkanyezi;
const perfumeSithelo = fragranceImages.sithelo;
const perfumeLangelihle = fragranceImages.langelihle;
const perfumeNdalwenhle = fragranceImages.ndalwenhle;
const perfumeLuyanda = fragranceImages.luyanda;
const perfumeHero = fragranceImages.product02;
const perfumeBasket = fragranceImages.product01;
const perfumePicnic = packageImages.product06;
const perfumeBottles = carouselImages.perfumeDisplay04;
const perfumeFloral = fragranceImages.product05;
const perfumeDiffuser = fragranceImages.product06;
const perfumeWrapped = fragranceImages.product07;
const hairStraight = hairImages.straightWig01;
const hairCurly = hairImages.kinkyWig01;
const laundryImage = hairImages.straightWig07;

export const PRODUCTS: Product[] = [
  {
    id: 'indoniyamanzi',
    name: 'Indoniyamanzi',
    subtitle: 'BISILE Eau de Parfum',
    eyebrow: 'Fragrance',
    price: 499.99,
    description: 'A BISILE fragrance made for everyday luxury and a memorable finishing ritual.',
    notes: ['Eau de Parfum', 'Be Luxury', 'Signature Scent'],
    image: perfumeIndoniyamanzi,
    secondaryImage: perfumeHero,
    tertiaryImage: perfumePicnic,
    galleryImages: [perfumeIndoniyamanzi, perfumeHero, perfumePicnic, perfumeFloral],
    imageFit: 'contain',
    category: 'parfum',
    collection: 'fragrance',
    isBestSeller: true,
  },
  {
    id: 'inkanyezi',
    name: 'Inkanyezi',
    subtitle: 'BISILE Eau de Parfum',
    eyebrow: 'Fragrance',
    price: 499.99,
    description: 'A polished fragrance for soft presence, daily wear, and quiet elegance.',
    notes: ['Eau de Parfum', 'Everyday Luxury', 'Soft Finish'],
    image: perfumeInkanyezi,
    secondaryImage: perfumeBottles,
    tertiaryImage: perfumeBasket,
    galleryImages: [perfumeInkanyezi, perfumeBottles, perfumeBasket, perfumeWrapped],
    imageFit: 'contain',
    category: 'parfum',
    collection: 'fragrance',
    isNew: true,
  },
  {
    id: 'sithelo',
    name: 'Sithelo',
    subtitle: 'BISILE Eau de Parfum',
    eyebrow: 'Fragrance',
    price: 649.99,
    description: 'A richer scent expression made for statement moments and lasting impressions.',
    notes: ['Eau de Parfum', 'Statement Scent', 'Luxury Finish'],
    image: perfumeSithelo,
    secondaryImage: perfumeBasket,
    tertiaryImage: perfumeFloral,
    galleryImages: [perfumeSithelo, perfumeBasket, perfumeFloral, perfumeHero],
    imageFit: 'contain',
    category: 'parfum',
    collection: 'fragrance',
  },
  {
    id: 'langelihle',
    name: 'Langelihle',
    subtitle: 'BISILE Eau de Parfum',
    eyebrow: 'Fragrance',
    price: 629.99,
    description: 'Warm, graceful, and refined. Langelihle completes a considered scent wardrobe.',
    notes: ['Eau de Parfum', 'Warm Trail', 'Be Luxury'],
    image: perfumeLangelihle,
    secondaryImage: perfumePicnic,
    tertiaryImage: perfumeBottles,
    galleryImages: [perfumeLangelihle, perfumePicnic, perfumeBottles, perfumeBasket],
    imageFit: 'contain',
    category: 'parfum',
    collection: 'fragrance',
  },
  {
    id: 'ndalwenhle',
    name: 'Ndalwenhle',
    subtitle: 'BISILE Eau de Parfum',
    eyebrow: 'Fragrance',
    price: 529.99,
    description: 'A clean everyday scent designed for subtle confidence and effortless wear.',
    notes: ['Eau de Parfum', 'Daily Ritual', 'Soft Finish'],
    image: perfumeNdalwenhle,
    secondaryImage: perfumeWrapped,
    tertiaryImage: perfumeBottles,
    galleryImages: [perfumeNdalwenhle, perfumeWrapped, perfumeBottles, perfumeDiffuser],
    imageFit: 'contain',
    category: 'parfum',
    collection: 'fragrance',
  },
  {
    id: 'luyanda',
    name: 'Luyanda',
    subtitle: 'BISILE Eau de Parfum',
    eyebrow: 'Fragrance',
    price: 689.99,
    description: 'A premium BISILE scent with a deeper profile for special days and evening rituals.',
    notes: ['Eau de Parfum', 'Premium Scent', 'Evening Ritual'],
    image: perfumeLuyanda,
    secondaryImage: perfumeDiffuser,
    tertiaryImage: perfumePicnic,
    galleryImages: [perfumeLuyanda, perfumeDiffuser, perfumePicnic, perfumeHero],
    imageFit: 'contain',
    category: 'parfum',
    collection: 'fragrance',
  },
  {
    id: 'mvelwenhle',
    name: 'Mvelwenhle',
    subtitle: 'Everyday Luxury Wig',
    eyebrow: '8 inch / 4x4 closure',
    price: 2489.99,
    description: '8 inch, 4x4 closure, natural black, 180% density, straight.',
    notes: ['Processed Virgin Hair', 'Natural Black', '180% Density'],
    image: hairStraight,
    secondaryImage: hairImages.straightWig02,
    category: 'wig',
    collection: 'hair',
    isBestSeller: true,
  },
  {
    id: 'thabitha',
    name: 'Thabitha',
    subtitle: 'Everyday Luxury Wig',
    eyebrow: '10 inch / 4x4 closure',
    price: 2649.99,
    description: '10 inch, 4x4 closure, natural black, 180% density, jerry curls.',
    notes: ['Processed Virgin Hair', 'Jerry Curls', '180% Density'],
    image: hairCurly,
    secondaryImage: hairStraight,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'nokhwezi',
    name: 'Nokhwezi',
    subtitle: 'Everyday Luxury Wig',
    eyebrow: '12 inch / 4x4 closure',
    price: 2799.99,
    description: '12 inch, 4x4 closure, natural black, 180% density, waterwave curls.',
    notes: ['Processed Virgin Hair', 'Waterwave Curls', '180% Density'],
    image: hairCurly,
    secondaryImage: hairStraight,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'khwezilokusa',
    // TODO: Confirm spelling. Extracted text says "Khwezilikusa".
    name: 'Khwezilikusa',
    subtitle: 'Soft Luxurious Quality Wig',
    eyebrow: '8 inch / Glueless lace',
    price: 2799.99,
    description: '8 inch, 4x4 closure, glueless lace, bob straight, 180% density, natural black.',
    notes: ['Processed Virgin Hair', 'Bob Straight', 'Glueless Lace'],
    image: hairStraight,
    secondaryImage: hairImages.straightWig04,
    category: 'wig',
    collection: 'hair',
    isNew: true,
  },
  {
    id: 'nobuntu',
    name: 'Nobuntu',
    subtitle: 'Soft Luxurious Quality Wig',
    eyebrow: '10 inch / 5x5 closure',
    price: 2949.99,
    description: '10 inch, 5x5 closure, glueless lace, straight, 180% density, natural black.',
    notes: ['Processed Virgin Hair', 'Straight', '5x5 Closure'],
    image: hairStraight,
    secondaryImage: hairCurly,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'melokuhle',
    name: 'Melokuhle',
    subtitle: 'Soft Luxurious Quality Wig',
    eyebrow: '12 inch / HD lace',
    price: 3549.99,
    description: '12 inch, 5x5 closure, HD lace, bob straight, 130% density, colour #4, blunt cut.',
    notes: ['Processed Virgin Hair', 'HD Lace', 'Colour #4'],
    image: hairStraight,
    secondaryImage: hairImages.straightWig08,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'ntando',
    name: 'Ntando',
    subtitle: 'Soft Luxurious Quality Wig',
    eyebrow: '12 inch / HD lace',
    price: 3749.99,
    description: '12 inch, 5x5 closure, HD lace, waterwave curls, 180% density, colour #30.',
    notes: ['Processed Virgin Hair', 'Waterwave Curls', 'Colour #30'],
    image: hairCurly,
    secondaryImage: hairStraight,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'ayabonga',
    name: 'Ayabonga',
    subtitle: 'Soft Luxurious Quality Wig',
    eyebrow: '16 inch / 4x4 closure',
    price: 3449.99,
    description: '16 inch, 4x4 closure, glueless lace, natural black, 180% density, jerry curls.',
    notes: ['Processed Virgin Hair', 'Jerry Curls', 'Glueless Lace'],
    image: hairCurly,
    secondaryImage: hairImages.curlyBundle01,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'ayanda',
    name: 'Ayanda',
    subtitle: 'Soft Luxurious Quality Wig',
    eyebrow: '18 inch / 4x4 closure',
    price: 3799.99,
    description: '18 inch, 4x4 closure, glueless lace, natural black, 180% density, jerry curls.',
    notes: ['Processed Virgin Hair', 'Jerry Curls', 'Natural Black'],
    image: hairCurly,
    secondaryImage: hairStraight,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'bonginhlanhla',
    name: 'Bonginhlanhla',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '12 inch / 5x5 closure',
    price: 3789.99,
    description: '12 inch, 5x5 closure, HD lace, bob straight, blunt cut, natural black, 180% density.',
    notes: ['Processed Virgin Hair', 'Premium Luxury', 'HD Lace'],
    image: hairStraight,
    secondaryImage: hairImages.straightWig10,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'nobuhle',
    name: 'Nobuhle',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '10 inch / 13x4 closure',
    price: 3949.99,
    description: '10 inch, 13x4 closure, HD lace, bob straight, 180% density, natural black.',
    notes: ['Processed Virgin Hair', '13x4 Closure', 'HD Lace'],
    image: hairStraight,
    secondaryImage: hairCurly,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'masindi',
    name: 'Masindi',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '16 inch / 13x4 closure',
    price: 4649.99,
    description: '16 inch, 13x4 closure, HD lace, straight, 180% density, natural black, blunt cut.',
    notes: ['Processed Virgin Hair', 'Straight', 'Blunt Cut'],
    image: hairStraight,
    secondaryImage: hairImages.straightWig11,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'buhlebendalo',
    name: 'Buhlebendalo',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '14 inch / 13x4 closure',
    price: 4549.99,
    description: '14 inch, 13x4 closure, HD lace, kinky jerry curl, 180% density, natural colour.',
    notes: ['Processed Virgin Hair', 'Kinky Jerry Curl', 'Natural Colour'],
    image: hairCurly,
    secondaryImage: hairStraight,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'thabisile',
    name: 'Thabisile',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '12 inch / 13x4 closure',
    price: 4249.99,
    description: '12 inch, 13x4 closure, HD lace, bob straight, blunt cut, 130% density, ombre natural black roots and #4.',
    notes: ['Processed Virgin Hair', 'Ombre', 'Blunt Cut'],
    image: hairStraight,
    secondaryImage: hairImages.kinkyWig02,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'ntombi-zandile',
    name: 'Ntombi Zandile',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '18 inch / 13x4 closure',
    price: 4489.99,
    description: '18 inch, 13x4 closure, HD lace, straight, natural black, 180% density, jerry curls.',
    notes: ['Processed Virgin Hair', 'HD Lace', 'Natural Black'],
    image: hairStraight,
    secondaryImage: hairCurly,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'londiwe',
    name: 'Londiwe',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '20 inch / 13x4 closure',
    price: 4689.99,
    description: '20 inch, 13x4 closure, HD lace, straight, 180% density, ombre natural black and #30.',
    notes: ['Processed Virgin Hair', 'Ombre', 'Colour #30'],
    image: hairStraight,
    secondaryImage: hairImages.straightWig06,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'samkelisiwe',
    name: 'Samkelisiwe',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '20 inch / 13x4 closure',
    price: 4849.99,
    description: '20 inch, 13x4 closure, HD lace, waterwave curls, 180% density, natural black.',
    notes: ['Processed Virgin Hair', 'Waterwave Curls', 'Natural Black'],
    image: hairCurly,
    secondaryImage: hairStraight,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'ntombizonke',
    name: 'Ntombizonke',
    subtitle: 'Premium Luxury Wig',
    eyebrow: '18 inch / 13x4 closure',
    price: 4889.99,
    description: '18 inch, 13x4 closure, HD lace, kinky jerry curls, 200% density, natural black.',
    notes: ['Processed Virgin Hair', 'Kinky Jerry Curls', '200% Density'],
    image: hairCurly,
    secondaryImage: hairImages.kinkyWig04,
    category: 'wig',
    collection: 'hair',
  },
  {
    id: 'wig-wash-only',
    name: 'Wig Wash Only',
    subtitle: 'Laundry Service',
    eyebrow: 'Wash service',
    price: 190,
    description: 'Professional wig wash service.',
    notes: ['Wash Service', 'BISILE Laundry'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'wig-treatment-straighten',
    name: 'Wig Treatment - Straighten',
    subtitle: 'Laundry Service',
    eyebrow: 'Wash service',
    price: 200,
    description: 'Wig treatment with straightening finish.',
    notes: ['Treatment', 'Straighten'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'wig-treatment-curls',
    name: 'Wig Treatment - Curls',
    subtitle: 'Laundry Service',
    eyebrow: 'Wash service',
    price: 250,
    description: 'Wig treatment with curl refresh.',
    notes: ['Treatment', 'Curls'],
    image: laundryImage,
    secondaryImage: hairCurly,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'straightening-only',
    name: 'Straightening Only',
    subtitle: 'Laundry Service',
    eyebrow: 'Styling',
    price: 100,
    description: 'Straightening service for your wig.',
    notes: ['Styling', 'Straightening'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'curls-activation-only',
    name: 'Curls Activation Only',
    subtitle: 'Laundry Service',
    eyebrow: 'Styling',
    price: 180,
    description: 'Curl activation service for refreshed movement and shape.',
    notes: ['Styling', 'Curl Activation'],
    image: laundryImage,
    secondaryImage: hairCurly,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'frontal-plucking-only',
    name: 'Frontal Plucking Only',
    subtitle: 'Laundry Service',
    eyebrow: 'Customisation',
    price: 100,
    description: 'Frontal plucking customisation.',
    notes: ['Customisation', 'Frontal Plucking'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'plucking-straightening',
    name: 'Plucking and Straightening',
    subtitle: 'Laundry Service',
    eyebrow: 'Customisation',
    price: 200,
    description: 'Plucking and straightening customisation package.',
    notes: ['Customisation', 'Straightening'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'plucking-curl-activation',
    name: 'Plucking and Curl Activation',
    subtitle: 'Laundry Service',
    eyebrow: 'Customisation',
    price: 270,
    description: 'Plucking and curl activation customisation package.',
    notes: ['Customisation', 'Curl Activation'],
    image: laundryImage,
    secondaryImage: hairCurly,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'custom-parting',
    name: 'Custom Parting',
    subtitle: 'Laundry Service',
    eyebrow: 'Customisation',
    price: 100,
    description: 'Custom parting service for your wig.',
    notes: ['Customisation', 'Parting'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'straight-to-custom-curls',
    name: 'Straight to Custom Curls',
    subtitle: 'Laundry Service',
    eyebrow: 'Customisation',
    price: 320,
    description: 'Convert a straight finish into custom curls.',
    notes: ['Customisation', 'Custom Curls'],
    image: laundryImage,
    secondaryImage: hairCurly,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'wig-bundles-dye',
    name: 'Wig / Bundles Dye',
    subtitle: 'Laundry Service',
    eyebrow: 'Customisation',
    price: 300,
    description: 'Dye service for wigs or bundles.',
    notes: ['Customisation', 'Dye'],
    image: laundryImage,
    secondaryImage: hairImages.curlyBundle02,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'full-laundry-straight',
    name: 'Full Laundry Package - Straight',
    subtitle: 'Laundry Service',
    eyebrow: 'Full laundry package',
    price: 390,
    description: 'Wig wash, plucking, and straightening.',
    notes: ['Wash', 'Plucking', 'Straightening'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'full-laundry-curls',
    name: 'Full Laundry Package - Curls',
    subtitle: 'Laundry Service',
    eyebrow: 'Full laundry package',
    price: 420,
    description: 'Wig wash, plucking, and curls activation.',
    notes: ['Wash', 'Plucking', 'Curls Activation'],
    image: laundryImage,
    secondaryImage: hairCurly,
    category: 'laundry',
    collection: 'service',
  },
  {
    id: 'full-laundry-custom-part',
    name: 'Full Laundry Package - Custom Part',
    subtitle: 'Laundry Service',
    eyebrow: 'Full laundry package',
    price: 590,
    description: 'Wig wash, plucking, custom parting, and straighten or curl activation.',
    notes: ['Wash', 'Plucking', 'Custom Parting'],
    image: laundryImage,
    secondaryImage: hairStraight,
    category: 'laundry',
    collection: 'service',
  },
];

export const FRAGRANCE_PRODUCTS = PRODUCTS.filter((product) => product.collection === 'fragrance');
export const WIG_PRODUCTS = PRODUCTS.filter((product) => product.collection === 'hair' && product.category === 'wig');
export const HAIR_PRODUCTS = WIG_PRODUCTS;
export const CONFIGURABLE_HAIR_PRODUCTS = [...BUNDLE_PRODUCTS, CLOSURE_PRODUCT, WIG_LAUNDRY_PRODUCT];
export const ALL_HAIR_PRODUCTS = [...WIG_PRODUCTS, ...CONFIGURABLE_HAIR_PRODUCTS];
export const SERVICE_PRODUCTS = [WIG_LAUNDRY_PRODUCT];

export const DELIVERY_OPTIONS = [
  { name: 'PostNet to PostNet', price: 'R109,99' },
  { name: 'PAXI to PAXI', price: 'R109,99' },
  { name: 'Courier GUY (PUDO)', price: 'R149,99 +/- depending on your address' },
  { name: 'PostNet to Address', price: 'R349,99 +/- depending on your address' },
  { name: 'International Delivery', price: `Enquire about international delivery at ${CONTACT_EMAIL}` },
];

export const LAYBYE_TERMS = [
  'Laybye is available for a maximum period of 3 months only.',
  'A minimum deposit of 50% is required to secure your order.',
  'The remaining 50% balance will be split into two payments of 25% over the next 2 months.',
  'Monthly instalments must be paid on the agreed due dates.',
  'Products will only be released once full payment has been received and cleared.',
  'No changes to the order may be made once the laybye has been confirmed.',
  'Payments made are non-refundable if the laybye is cancelled by the customer.',
  'Missed or late payments may result in cancellation of the laybye order and forfeiture of amounts paid.',
  'Prices are fixed once the 50% deposit has been paid.',
  'Promotional discounts cannot be applied after the laybye has been opened.',
  'Please send proof of payment after each instalment.',
  'Collection or delivery arrangements will be made once the balance is fully paid.',
];

export const BUNDLE_PRICE_GROUPS = [
  { title: 'Single Straight Bundles', rows: [['10"', 'R 799,99'], ['12"', 'R 999,99'], ['16"', 'R 1 199,99'], ['18"', 'R 1 399,99'], ['20"', 'R 1 599,99'], ['22"', 'R 1 799,99']] },
  { title: 'Single Kinky Curls Bundles', rows: [['10"', 'R 899,99'], ['12"', 'R 1 099,99'], ['16"', 'R 1 399,99'], ['18"', 'R 1 699,99'], ['20"', 'R 1 999,99'], ['22"', 'R 2 299,99']] },
  { title: 'Single Waterwave Curls Bundles', rows: [['10"', 'R 1 049,99'], ['12"', 'R 1 299,99'], ['16"', 'R 1 549,99'], ['18"', 'R 1 799,99'], ['20"', 'R 2 049,99'], ['22"', 'R 2 299,99']] },
  { title: 'Three Straight Bundles', rows: [['10"', 'R 2 099,99'], ['12"', 'R 2 399,99'], ['16"', 'R 2 699,99'], ['18"', 'R 2 999,99'], ['20"', 'R 3 299,99'], ['22"', 'R 3 599,99']] },
  { title: 'Three Kinky Curls Bundles', rows: [['10"', 'R 1 799,99'], ['12"', 'R 2 699,99'], ['16"', 'R 3 599,99'], ['18"', 'R 4 499,99'], ['20"', 'R 5 399,99'], ['22"', 'R 6 299,99']] },
  { title: 'Three Waterwave Curls Bundles', rows: [['10"', 'R 2 249,99'], ['12"', 'R 2 899,99'], ['16"', 'R 3 449,99'], ['18"', 'R 3 799,99'], ['20"', 'R 4 349,99'], ['22"', 'R 4 899,99']] },
];

export const CLOSURE_PRICE_GROUPS = [
  { title: 'Straight 4x4 Closure', rows: [['10"', 'R 449,99'], ['12"', 'R 549,99']] },
  { title: 'Kinky Curl 4x4 Closure', rows: [['10"', 'R 549,99'], ['12"', 'R 649,99']] },
  { title: 'Waterwave Curl 4x4 Closure', rows: [['10"', 'R 549,99'], ['12"', 'R 649,99']] },
  { title: 'Straight 13x4 Closure', rows: [['10"', 'R 599,99'], ['12"', 'R 649,99']] },
  { title: 'Kinky Curl 13x4 Closure', rows: [['10"', 'R 699,99'], ['12"', 'R 749,99']] },
  { title: 'Waterwave Curl 13x4 Closure', rows: [['10"', 'R 699,99'], ['12"', 'R 749,99']] },
];
