services:
  - type: web
    name: bisile-api
    runtime: node
    buildCommand: npm install && npm --prefix server install && npm run build && npm --prefix server run build
    startCommand: npm --prefix server start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: TEMP_NETLIFY_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: bisile
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
