export const shippingOptions = [
  { id: 'postnet-to-postnet', name: 'PostNet to PostNet', price: 109.99, description: 'Branch-to-branch delivery', isActive: true },
  { id: 'paxi-to-paxi', name: 'PAXI to PAXI', price: 109.99, description: 'Counter-to-counter parcel delivery', isActive: true },
  { id: 'courier-guy-pudo', name: 'Courier GUY (PUDO)', price: 149.99, description: 'Price may vary depending on your address', isActive: true },
  { id: 'postnet-to-address', name: 'PostNet to Address', price: 349.99, description: 'Price may vary depending on your address', isActive: true },
];

export const categories = [
  { name: 'Fragrance', slug: 'fragrance', description: 'BISILE eau de parfum and scent rituals', isActive: true },
  { name: 'Hair', slug: 'hair', description: 'Processed virgin hair and BISILE hair services', isActive: true },
  { name: 'Wigs', slug: 'wigs', description: 'Bhelekazi wig collection', isActive: true },
  { name: 'Bundles', slug: 'bundles', description: 'Processed virgin hair bundles', isActive: true },
  { name: 'Closures & Frontals', slug: 'closures-frontals', description: 'Premium lace closures and frontals', isActive: true },
  { name: 'Wig Laundry', slug: 'wig-laundry', description: 'BISILE wig washing, treatment, and styling services', isActive: true },
];

export const products = [
  { id: 'indoniyamanzi', name: 'Indoniyamanzi', slug: 'indoniyamanzi', price: 499.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'inkanyezi', name: 'Inkanyezi', slug: 'inkanyezi', price: 499.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'sithelo', name: 'Sithelo', slug: 'sithelo', price: 649.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'langelihle', name: 'Langelihle', slug: 'langelihle', price: 629.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'ndalwenhle', name: 'Ndalwenhle', slug: 'ndalwenhle', price: 529.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'luyanda', name: 'Luyanda', slug: 'luyanda', price: 689.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'discovery-set', name: 'Discovery Set', slug: 'discovery-set', price: 349.99, stock: 20, category: 'parfum', collection: 'fragrance' },
  { id: 'mvelwenhle', name: 'Mvelwenhle', slug: 'mvelwenhle', price: 2489.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'thabitha', name: 'Thabitha', slug: 'thabitha', price: 2649.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'nokhwezi', name: 'Nokhwezi', slug: 'nokhwezi', price: 2799.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'khwezilokusa', name: 'Khwezilokusa', slug: 'khwezilokusa', price: 2799.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'nobuntu', name: 'Nobuntu', slug: 'nobuntu', price: 2949.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'melokuhle', name: 'Melokuhle', slug: 'melokuhle', price: 3549.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'ntando', name: 'Ntando', slug: 'ntando', price: 3749.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'ayabonga', name: 'Ayabonga', slug: 'ayabonga', price: 3449.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'ayanda', name: 'Ayanda', slug: 'ayanda', price: 3799.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'bonginhlanhla', name: 'Bonginhlanhla', slug: 'bonginhlanhla', price: 3789.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'nobuhle', name: 'Nobuhle', slug: 'nobuhle', price: 3949.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'masindi', name: 'Masindi', slug: 'masindi', price: 4649.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'buhlebendalo', name: 'Buhlebendalo', slug: 'buhlebendalo', price: 4549.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'thabisile', name: 'Thabisile', slug: 'thabisile', price: 4249.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'ntombi-zandile', name: 'Ntombi Zandile', slug: 'ntombi-zandile', price: 4489.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'londiwe', name: 'Londiwe', slug: 'londiwe', price: 4689.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'samkelisiwe', name: 'Samkelisiwe', slug: 'samkelisiwe', price: 4849.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'ntombizonke', name: 'Ntombizonke', slug: 'ntombizonke', price: 4889.99, stock: 4, category: 'wig', collection: 'hair' },
  { id: 'single-bundle', name: 'Single Bundle', slug: 'single-bundle', price: 799.99, stock: 10, category: 'bundle', collection: 'hair' },
  { id: 'three-bundles', name: 'Three Bundles', slug: 'three-bundles', price: 1799.99, stock: 10, category: 'bundle', collection: 'hair' },
  { id: 'closures-frontals', name: 'Closures & Frontals', slug: 'closures-frontals', price: 449.99, stock: 10, category: 'closure', collection: 'hair' },
  { id: 'wig-laundry', name: 'Wig Laundry', slug: 'wig-laundry', price: 190, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'wig-wash-only', name: 'Wig Wash Only', slug: 'wig-wash-only', price: 190, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'wig-treatment-straighten', name: 'Wig Treatment (Straighten)', slug: 'wig-treatment-straighten', price: 200, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'wig-treatment-curls', name: 'Wig Treatment (Curls)', slug: 'wig-treatment-curls', price: 250, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'straightening-only', name: 'Straightening Only', slug: 'straightening-only', price: 100, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'curls-activation-only', name: 'Curls Activation Only', slug: 'curls-activation-only', price: 180, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'frontal-plucking-only', name: 'Frontal Plucking Only', slug: 'frontal-plucking-only', price: 100, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'plucking-straightening', name: 'Plucking & Straightening', slug: 'plucking-straightening', price: 200, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'plucking-curl-activation', name: 'Plucking & Curl Activation', slug: 'plucking-curl-activation', price: 270, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'custom-parting', name: 'Custom Parting', slug: 'custom-parting', price: 100, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'straight-to-custom-curls', name: 'Straight to Custom Curls', slug: 'straight-to-custom-curls', price: 320, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'wig-bundles-dye', name: 'Wig / Bundles dye', slug: 'wig-bundles-dye', price: 300, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'full-laundry-straight', name: 'Wig Wash, Plucking, & Straightening', slug: 'full-laundry-straight', price: 390, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'full-laundry-curls', name: 'Wig Wash, Plucking, & Curls Activation', slug: 'full-laundry-curls', price: 420, stock: 99, category: 'laundry', collection: 'service' },
  { id: 'full-laundry-custom-part', name: 'Wig Wash, Plucking, Custom Parting, & Straighten / Curl Activation', slug: 'full-laundry-custom-part', price: 590, stock: 99, category: 'laundry', collection: 'service' },
];
