import React, { useState } from 'react';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { FadeIn } from '../components/UI/FadeIn';

export const Community: React.FC = () => {
  const [submitted, setSubmitted] = useState(false);
  return <div className="min-h-screen bg-secondary pt-20 text-primary">
    <section className="grid md:grid-cols-2"><div className="flex items-center px-7 py-20 md:px-16"><FadeIn><p className="mb-3 text-[10px] uppercase tracking-[0.22em] text-accent">The BISILE circle</p><h1 className="font-serif text-6xl leading-[0.9] md:text-8xl">Create with intention.</h1><p className="mt-6 max-w-lg text-sm leading-7 text-primary/60">We work with creators whose point of view feels considered, honest, and beautifully their own.</p></FadeIn></div><div className="min-h-[520px] overflow-hidden"><img src="/media/bisile/hero-perfume.jpg" alt="BISILE creator community" className="editorial-image h-full w-full object-cover" /></div></section>
    <section className="bg-secondary px-6 py-20 md:px-12"><div className="mx-auto grid max-w-[1120px] gap-12 md:grid-cols-[0.8fr_1.2fr]"><div><p className="mb-3 text-[10px] uppercase tracking-[0.22em] text-accent">Applications</p><h2 className="font-serif text-5xl">Join the circle.</h2><p className="mt-5 text-sm leading-7 text-primary/60">You do not need a massive audience. We are interested in fit, feeling, and thoughtful storytelling.</p></div>{submitted ? <div className="border border-black/10 bg-white p-8"><CheckCircle2 className="mb-4 text-accent" /><h3 className="font-subhead text-3xl">Your application is with us.</h3></div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }} className="grid gap-4 sm:grid-cols-2"><input required placeholder="Full name" className="field-light px-4 py-4 text-xs" /><input required type="email" placeholder="Email address" className="field-light px-4 py-4 text-xs" /><input required placeholder="Primary social handle" className="field-light px-4 py-4 text-xs" /><select required defaultValue="" className="field-light px-4 py-4 text-xs"><option value="" disabled>Primary platform</option><option>Instagram</option><option>TikTok</option><option>YouTube</option></select><textarea required rows={5} placeholder="Tell us about your content and community" className="field-light px-4 py-4 text-xs sm:col-span-2" /><button className="flex items-center justify-between bg-primary px-5 py-4 text-[10px] uppercase tracking-[0.18em] text-white hover:bg-accent sm:col-span-2">Submit application <ArrowRight size={14} /></button></form>}</div></section>
  </div>;
};
